### ISSUE TITLE
Adapter Startup-Crash with 'res' being null here

### ISSUE THREAD

**Issue by fabian-barney** [hobbyquaker/binrpc#3]
https://github.com/hobbyquaker/binrpc/blob/1afb7869ee0777a1a3544c3c15b4b382465364d9/lib/protocol.js#L414

My iobroker hm-rpc adapter crashes on startup with BIN-RPc enabled. In fact it is a NPE in the line above and 'res' is null. Commenting out the logging fixed the problem and everything works like a charm.

I am using the iobroker HM-RPC adapter to connect to Homegear.
Further information here: http://forum.iobroker.net/viewtopic.php?p=115883#p115883

**Comment by Apollon77** [comment]
Problem is that ioBroker is still at 1.0.0 of the library, so it will be quite hard :-(
We also have another null problem with Homegear (or the same?):

```
2018-02-07 23:19:34.675 - error: Caught by controller[0]: TypeError: Cannot read property 'toString' of null
2018-02-07 23:19:34.676 - error: Caught by controller[0]: at Object.decodeData (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/protocol.js:371:82)
2018-02-07 23:19:34.676 - error: Caught by controller[0]: at rec (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/protocol.js:432:32)
2018-02-07 23:19:34.676 - error: Caught by controller[0]: at Object.decodeStrangeRequest (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/protocol.js:441:9)
2018-02-07 23:19:34.676 - error: Caught by controller[0]: at Object.decodeRequest (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/protocol.js:476:32)
2018-02-07 23:19:34.676 - error: Caught by controller[0]: at Socket. (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/server.js:50:38)
2018-02-07 23:19:34.676 - error: Caught by controller[0]: at emitOne (events.js:116:13)
2018-02-07 23:19:34.676 - error: Caught by controller[0]: at Socket.emit (events.js:211:7)
2018-02-07 23:19:34.676 - error: Caught by controller[0]: at addChunk (_stream_readable.js:263:12)
2018-02-07 23:19:34.676 - error: Caught by controller[0]: at readableAddChunk (_stream_readable.js:250:11)
2018-02-07 23:19:34.676 - error: Caught by controller[0]: at Socket.Readable.push (_stream_readable.js:208:10)
```
may be something comparable.

I check upgrading the library in ioBroker, then we see again

**Comment by fabian-barney** [comment]
It is most probably the same issue. It is the same line of code and that line of code contains nothing else than the logging statement I posted above.
And may be that 'dataType' is null with you and not 'res' being null like with me. But I do not think so. I had the exact same stacktrace.

**Comment by Apollon77** [comment]
I will send in a PR later on to fix this
